_index:
    path: /
    defaults: { _controller: AccountBundle:Transaction:index }

account:
    resource: "@AccountBundle/Controller/"
    type:     annotation
    prefix:   /

account_rest:
    type: rest
    resource: Ebank\Bundles\AccountBundle\Controller\Api\Rest\AccountController

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"