<?php

namespace Ebank\Bundles\AccountBundle\Repository;

use Ebank\Bundles\UserBundle\Entity\User;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAccountsForUser(User $user)
    {

        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.owner = :user')
            ->orWhere(':user MEMBER OF a.disponents')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }
}
