<?php

namespace Ebank\Bundles\AccountBundle\Repository;

use Ebank\Bundles\UserBundle\Entity\User;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTransactionForUser(User $user)
    {

        $qb = $this->createQueryBuilder('t');
        $qb
            ->join('AccountBundle:Account', 'af', 'WITH', $qb->expr()->eq('t.accountFrom', 'af.id'))
            ->join('AccountBundle:Account', 'at', 'WITH', $qb->expr()->eq('t.accountTo', 'at.id'))
            ->where('t.user = :user')
            ->orWhere('af.owner = :user')
            ->orWhere('at.owner = :user')
            ->orWhere(':user MEMBER OF af.disponents')
            ->orWhere(':user MEMBER OF at.disponents')
            ->setParameter('user', $user)
            ->orderBy('t.date')
        ;

        return $qb->getQuery()->getResult();
    }
}
